In [72]:
import pandas as pd
import numpy as np

df_vendas = pd.read_csv("vendas_tech.csv", encoding="utf-8", low_memory=False)
display(df_vendas)
df_gerentes = pd.read_excel("gerentes_lojas.xlsx")
display(df_gerentes)

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

             Loja   Gerente  Meta_Mensal
0       São Paulo    Carlos        50000
1  Rio de Janeiro  Fernanda        60000
2        Curitiba   Roberto        45000
3  Belo Horizonte   Juliana        55000
4          Recife    Marcos        48000
5    Porto Alegre     Pedro        42000
6        Salvador       Ana        52000

In [73]:
#inspeção geral
display(df_vendas)
#inspeção () 5 primeiras linhas do arquivo ou (10)
display(df_vendas.head(10))
#inspeção final do arquivo () 5 primeiras linhas do arquivo ou (10) 
display(df_vendas.tail(10))
#inspeção dados aleatórios
display(df_vendas.sample(10))
#saber a quantidade de linhas do arquivo
display(df_vendas.shape)
#ver todas as colunas do arquivo
display(df_vendas.columns) 
#ver todas as colunas do arquivo como lista
display(list(df_vendas.columns))
#info e describe
display(df_vendas.info())
display(df_vendas.describe())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
...,...,...,...,...,...,...,...,...
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,2025-01-01
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,NaN
2,3,2023-02-25,NaN,"Monitor 27""",1200.0,1,Cliente_14859,NaN
3,4,2024-11-19,RIO DE JANEIRO,Mouse Gamer,120.0,2,Cliente_17343,NaN
4,5,2024-01-27,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,NaN
5,6,2023-03-11,São Paulo,Cabo HDMI,40.0,1,Cliente_24809,NaN
6,7,2024-12-08,Salvador,"Monitor 27""",1200.0,1,Cliente_11076,NaN
7,8,2024-09-12,São Paulo,"Monitor 27""",1200.0,2,Cliente_14053,NaN
8,9,2023-05-20,Belo Horizonte,Mouse Gamer,120.0,1,Cliente_19175,NaN
9,10,2024-10-16,Recife,Notebook HP,3200.0,1,Cliente_13508,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
100090,15752,2023-03-20,Curitiba,"Monitor 27""",1200.0,1,Cliente_356,NaN
100091,4801,2023-10-29,São Paulo,Smartphone Samsung,2200.0,1,Cliente_5799,NaN
100092,89541,2023-09-01,Porto Alegre,"Monitor 27""",1200.0,1,Cliente_24144,NaN
100093,77528,2024-03-30,São Paulo,"Monitor 27""",1200.0,3,Cliente_5144,NaN
100094,32853,2024-04-10,Salvador,Smartphone Samsung,2200.0,2,Cliente_29799,NaN
100095,94091,2023-10-20,Porto Alegre,iPhone 14,5500.0,1,Cliente_11755,NaN
100096,52883,2024-03-17,Porto Alegre,Notebook Dell,3500.0,2,Cliente_12879,NaN
100097,65070,2023-06-19,Belo Horizonte,Smartphone Samsung,2200.0,2,Cliente_8160,NaN
100098,94031,2024-06-14,Salvador,iPhone 14,5500.0,2,Cliente_28545,NaN
100099,36755,2023-01-03,São Paulo,Notebook HP,3200.0,2,Cliente_3274,NaN

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Data_Base
89469,89470,2023-08-08,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_19286,NaN
22305,22306,2023-05-30,Recife,Mouse Gamer,120.0,1,Cliente_779,NaN
89671,89672,2023-01-22,RIO DE JANEIRO,"Monitor 27""",1200.0,2,Cliente_28411,NaN
70706,70707,2024-04-25,Belo Horizonte,Teclado Mecânico,250.0,1,Cliente_18427,NaN
36412,36413,2024-06-17,Recife,Notebook Dell,3500.0,3,Cliente_6703,NaN
76376,76377,2023-07-10,Rio de Janeiro,Notebook Dell,3500.0,1,Cliente_24342,NaN
90853,90854,2023-02-13,Rio de Janeiro,Smartphone Samsung,2200.0,1,Cliente_9330,NaN
10492,10493,2023-12-22,Salvador,Mouse Gamer,120.0,2,Cliente_16244,NaN
79936,79937,2023-08-07,Porto Alegre,Notebook HP,3200.0,1,Cliente_20139,NaN
49863,49864,2023-03-23,Recife,Cabo HDMI,40.0,1,Cliente_17879,NaN

(100100, 8)

Index(['ID_Pedido', 'Data', 'Loja', 'Produto', 'Preco_Unitario', 'Qtd',
       'Cliente', 'Data_Base'],
      dtype='str')

['ID_Pedido',
 'Data',
 'Loja',
 'Produto',
 'Preco_Unitario',
 'Qtd',
 'Cliente',
 'Data_Base']

<class 'pandas.DataFrame'>
RangeIndex: 100100 entries, 0 to 100099
Data columns (total 8 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100100 non-null  int64
 1   Data            100100 non-null  str
 2   Loja            98099 non-null   str
 3   Produto         100100 non-null  str
 4   Preco_Unitario  100100 non-null  float64
 5   Qtd             100100 non-null  int64
 6   Cliente         100100 non-null  str
 7   Data_Base       1 non-null       str
dtypes: float64(1), int64(2), str(5)
memory usage: 10.4 MB

None

           ID_Pedido  Preco_Unitario            Qtd
count  100100.000000   100100.000000  100100.000000
mean    50004.810180     2000.204595       1.499101
std     28866.872543     1841.050733       1.241605
min         1.000000       40.000000       1.000000
25%     25008.750000      120.000000       1.000000
50%     50004.500000     1200.000000       1.000000
75%     75002.250000     3200.000000       1.000000
max    100000.000000     5500.000000      10.000000

In [74]:
#tratamento de dados
#display(df_vendas["Loja"])
#display(df_vendas[["Loja","Cliente"]])
#colunas
df_analise = df_vendas.drop(columns=["Data_Base"])
#joga fora da tabela os nulos
#df_analise = df_analise.dropna()
#df_analise["Loja"] = df_analise["Loja"].fillna("Online")
#tipos de dados
df_analise["Data"] = pd.to_datetime(df_analise["Data"], format="%Y-%m-%d", errors="coerce")
#padronização
#tirar espaço início e final
#df_analise["Loja"] = df_analise["Loja"].str.strip()
#primeira letra maiúscula
#df_analise["Loja"] = df_analise["Loja"].str.title()
#encadeamento
df_analise["Loja"] = df_analise["Loja"].fillna("Online").str.strip().str.title()
#registro duplicado
df_analise = df_analise.drop_duplicates(subset=["ID_Pedido", "Loja"],keep="first")
display(df_analise)
display(df_analise.info())

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377
...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 7 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   ID_Pedido       100000 non-null  int64
 1   Data            100000 non-null  datetime64[us]
 2   Loja            100000 non-null  str
 3   Produto         100000 non-null  str
 4   Preco_Unitario  100000 non-null  float64
 5   Qtd             100000 non-null  int64
 6   Cliente         100000 non-null  str
dtypes: datetime64[us](1), float64(1), int64(2), str(3)
memory usage: 8.7 MB

None

In [75]:
#criar nova coluna
#faturamento
df_analise["Faturamento"] = df_analise["Qtd"] * df_analise["Preco_Unitario"] 
#forma de venda
df_analise["Forma_de_Vendas"] = np.where(df_analise["Loja"]=="Online", "Online", "Presencial")
#região
display(df_analise["Loja"].unique()) 
#dicionário de de para  
dic_regioes = {
    'São Paulo': "Sudeste",
    'Belo Horizonte': "Sudeste", 
    'Online': "Online",
    'Rio De Janeiro': "Sudeste", 
    'Salvador': "Nordeste", 
    'Recife': "Nordeste",  
    'Curitiba': "Sul",  
    'Porto Alegre': "Sul"
}

df_analise["Região"] = df_analise["Loja"].map(dic_regioes)
                                
display(df_analise)
#mostra quantos valores vazios/nulos existem em cada coluna do DataFrame df_analise
display(df_analise.isna().sum())

<ArrowStringArray>
[     'São Paulo', 'Belo Horizonte',         'Online', 'Rio De Janeiro',
       'Salvador',         'Recife',       'Curitiba',   'Porto Alegre']
Length: 8, dtype: str

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Vendas,Região
0,1,2023-06-08,São Paulo,Mouse Gamer,120.0,1,Cliente_4095,120.0,Presencial,Sudeste
1,2,2023-03-01,Belo Horizonte,iPhone 14,5500.0,1,Cliente_8750,5500.0,Presencial,Sudeste
2,3,2023-02-25,Online,"Monitor 27""",1200.0,1,Cliente_14859,1200.0,Online,Online
3,4,2024-11-19,Rio De Janeiro,Mouse Gamer,120.0,2,Cliente_17343,240.0,Presencial,Sudeste
4,5,2024-01-27,Rio De Janeiro,Smartphone Samsung,2200.0,1,Cliente_23377,2200.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,99996,2023-01-24,São Paulo,Mouse Gamer,120.0,2,Cliente_13732,240.0,Presencial,Sudeste
99996,99997,2024-08-28,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_25058,40.0,Presencial,Sudeste
99997,99998,2024-03-18,Curitiba,Smartphone Samsung,2200.0,2,Cliente_28864,4400.0,Presencial,Sul
99998,99999,2023-11-04,Porto Alegre,iPhone 14,5500.0,1,Cliente_4205,5500.0,Presencial,Sul
99999,100000,2024-06-15,Curitiba,Teclado Mecânico,250.0,1,Cliente_12237,250.0,Presencial,Sul

ID_Pedido          0
Data               0
Loja               0
Produto            0
Preco_Unitario     0
Qtd                0
Cliente            0
Faturamento        0
Forma_de_Vendas    0
Região             0
dtype: int64

In [76]:
#analisar - filtrar
#ordernar a base pelo campo Data
#Faturamente ordenado decrescente
df_analise = df_analise.sort_values(
    by=["Data", "Faturamento"],
    ascending=[True, False]
)
#vai recriar a coluna de index ordenado menor para maior
#exclui o nome index da coluna
df_analise = df_analise.reset_index(drop=True)
#.loc: id pedido - localiza por nome da coluna e linha
id_pedido = 4
loja = df_analise.loc[3, "Loja"]
produto = df_analise.loc[3, "Produto"]
cliente = df_analise.loc[3, "Cliente"]
print(loja, produto, cliente)
#.iloc: id pedido - localiza por posição
id_pedido = 4
loja = df_analise.iloc[3, 2]
produto = df_analise.iloc[3, 3]
cliente = df_analise.iloc[3, 6]
print(loja, produto, cliente)
display(df_analise)

#exportar pedaços da base
#df_vendas_sp = df_analise["Loja"]

Recife iPhone 14 Cliente_8623
Recife iPhone 14 Cliente_8623

,ID_Pedido,Data,Loja,Produto,Preco_Unitario,Qtd,Cliente,Faturamento,Forma_de_Vendas,Região
0,6428,2023-01-01,Porto Alegre,iPhone 14,5500.0,10,Cliente_17114,55000.0,Presencial,Sul
1,29418,2023-01-01,São Paulo,iPhone 14,5500.0,5,Cliente_1329,27500.0,Presencial,Sudeste
2,83598,2023-01-01,Belo Horizonte,Smartphone Samsung,2200.0,10,Cliente_18330,22000.0,Presencial,Sudeste
3,6681,2023-01-01,Recife,iPhone 14,5500.0,3,Cliente_8623,16500.0,Presencial,Nordeste
4,12842,2023-01-01,Rio De Janeiro,iPhone 14,5500.0,3,Cliente_15716,16500.0,Presencial,Sudeste
...,...,...,...,...,...,...,...,...,...,...
99995,75695,2024-12-30,Porto Alegre,Cabo HDMI,40.0,1,Cliente_29587,40.0,Presencial,Sul
99996,78584,2024-12-30,Curitiba,Cabo HDMI,40.0,1,Cliente_21307,40.0,Presencial,Sul
99997,84927,2024-12-30,Salvador,Cabo HDMI,40.0,1,Cliente_8499,40.0,Presencial,Nordeste
99998,93317,2024-12-30,Rio De Janeiro,Cabo HDMI,40.0,1,Cliente_27808,40.0,Presencial,Sudeste
99999,96426,2024-12-30,Recife,Cabo HDMI,40.0,1,Cliente_13841,40.0,Presencial,Nordeste

In [77]:
#analisar por agrupamento